### ISSUE TITLE
MatchPlugin is completly broken with TM2020

### ISSUE THREAD

**Issue by AmazingBeu** [jonthekiller/ManiaControlPlugins#2]
It just doesn't work. Due to script path and other.

**Comment by jonthekiller** [comment]
I'm aware of this. There is a lot of changes on Nadeo side that broke the plugin. I'm still working on it but it takes times to test all combinaisons and keeping TM2 compatibility.

**Comment by AmazingBeu** [comment]
Maybe it's necessary to create a new plugin for TM2020 like you did for ScriptLoader ?

I am also trying to fix it and for at the moment I have found:
* the "setScriptName" and "getScriptName" functions do not work as for Maniaplanet.
* the "setModeScriptText" function does not work because the scripts are not stored in the file.
* Some game mode options do not appear to be available in this game.

**Comment by jonthekiller** [comment]
For the ScriptLoader, it was because I'm not the original developer, so I can't modify the initial version.

ManiaControl team would like to keep the compatibility for the core, so it's better if I can do the same for the plugins. 
As of today, I'm able to manage a match but there is some bugs on Nadeo side during the load of a gamemode that I need to bypass and after to make the tests before releasing a first version with limited gamemodes (TA, Cup, Rounds).

**Comment by jonthekiller** [comment]
Fixed with newer versions
